export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';



export const GET_PRODUCTS_SUCCESS  ='GET_RODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL     ='GET_RODUCTS_FAIL';
export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL   =' PRODUCT_DETAILS_FAIL';
export const ADD_PRODUCT_SUCCESS   ='ADD_ITEM_SUCCESS';
export const ADD_PRODUCT_FAIL      ='ADD_ITEM_FAIL';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_ITEM_SUCCESS';
export const UPDATE_PRODUCT_FAIL   ='UPDATE_ITEM_FAIL';
export const DELETE_PRODUCT_SUCCESS='DELETE_ITEM_SUCCESS';
export const DELETE_PRODUCT_FAIL   ='DELETE_ITEM_FAIL';