//Register

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
//Login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
// Logout
export const LOGOUT = "LOGOUT";
// Product
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const ITEM_DETAILS_REQUEST = " ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = " ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_FAIL = "  ITEM_DETAILS_FAIL";
export const ADD_ITEM_SUCCESS = "ADD_ ITEM_SUCCESS";
export const ADD_ITEM_FAIL = "ADD_ ITEM_FAIL";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ ITEM_SUCCESS";
export const UPDATE_ITEM_FAIL = "UPDATE_ ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETE_ ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ ITEM_FAIL";

// cart
export const GET_CART_SUCCESS         = "GET_CART_SUCCESS";
export const GET_CART_FAIL            = "GET_CART_FAIL";
export const ADD_TO_CART_SUCCESS      = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL         = "ADD_TO_CART_FAIL";
export const DELETE_FROM_CART_SUCCESS = " DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAIL    = " DELETE_FROM_CART_FAIL";

// order
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
export const CHECKOUT_SUCCESS = " CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";
